name: CI_BuildArtifact
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  buildDockerArtifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish WebBookingApp/WebBookingApp.csproj -c Release -o website
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
         name: website
         path: website/**
         if-no-files-found: error    
#            - name: Test
#              run: dotnet test --no-build --verbosity normal
#    
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/BookingAPI:0.0.1
#
#      - name: Deploy to Test Server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: ${{ secrets.SERVER_PORT }}
#          script: |
#            sudo docker pull daniel0k/BookingAPI:0.1.0
#            docker stop BookingAPI_test_latest_container
#            docker rm BookingAPI_test_latest_container
#            sudo docker run --name=BookingAPI_test_latest_container -d -p 82:80 daniel0k/BookingAPI:0.1.0
